name: Test

on:
  workflow_dispatch:
  push:

env:
  FIELD_ID: PVTF_lADOCOJGKs4AX9CyzgPUCoI
  SELECT_FIELD_ID: PVTSSF_lADOCOJGKs4AX9CyzgPUCro
  SELECT_OPTION_ID: 4b83566e
  SELECT_COMPLEX_FIELD_ID: PVTSSF_lADOCOJGKs4AX9CyzgVbXGE
  SELECT_COMPLEX_OPTION_ID: 0a479792

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Get field id
        id: get-field-id
        uses: ./
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          project-number: 1
          project-owner: infinite-automations
          field-name: Test Field
      - name: Test Get field id
        uses: nick-fields/assert-action@v2
        with:
          expected: ${{ env.FIELD_ID }}
          actual: ${{ steps.get-field-id.outputs.field-id }}
          comparison: exact
      - name: Get select option id
        id: get-select-option-id
        uses: ./
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          project-number: 1
          project-owner: infinite-automations
          field-name: Test select field
          select-option-name: Option1
      - name: Test Get select option id
        uses: nick-fields/assert-action@v2
        with:
          expected: ${{ env.SELECT_OPTION_ID }}
          actual: ${{ steps.get-select-option-id.outputs.select-option-id }}
          comparison: exact
      - name: Get Complex select option id
        id: get-complex-select-option-id
        uses: ./
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          project-number: 1
          project-owner: infinite-automations
          field-name: Test complex select field
          select-option-name: Complex Option 1
      - name: Test Get complex select option id
        uses: nick-fields/assert-action@v2
        with:
          expected: ${{ env.SELECT_COMPLEX_OPTION_ID }}
          actual: ${{ steps.get-complex-select-option-id.outputs.select-option-id }}
          comparison: exact
        
